# DEEP LEARNING
## Pytorch Basic

In [2]:
import torch

In [3]:
torch.cuda.is_available()

False

## Dataset with pytorch

In [4]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [6]:
df.shape

(150, 6)

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis = 1).values
y = le.fit_transform(df["Species"].values)
#Chia dữ liệu với test size = 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1)
y_test = torch.LongTensor(y_test).reshape(-1)

In [8]:
len(y_train)

120

In [9]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [10]:
import torch

In [11]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [12]:
#Định nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [13]:
y.grad_fn

In [14]:
#Thực hiện lan truyền ngược và tính toán các gradient
y.backward()

In [15]:
#8x^3 + 3x^2 + 6x + 5
x.grad

tensor(93.)

# BTVN 1:
#Cho y = 5x^5 + 6x^3 - 3x + 1. Cho biết độ dốc của đa thức trên ở điểm nào? 

In [16]:
# BTVN 1: Tính đạo hàm của y = 5x^5 + 6x^3 - 3x + 1 tại x = 2
x = torch.tensor(2.0, requires_grad=True)
y = 5*x**5 + 6*x**3 - 3*x + 1
y.backward()
print("Đạo hàm tại x=2:", x.grad)

Đạo hàm tại x=2: tensor(469.)


# BTVN 2:
Tạo một tensor ban đầu có giá trị là 2
Định nghĩa hàm số và tính gradient
y = x^3 2x^2 + 5x + 1
hãy tính dy/dx tại giá trị của x
Dùng phương pháp Gradient Descent với Learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp

In [17]:
# BTVN 2: Gradient Descent cho y = x^3 + 2*x^2 + 5*x + 1
x = torch.tensor(2.0, requires_grad=True)
alpha = 0.1
for i in range(10):
    y = x**3 + 2*x**2 + 5*x + 1
    y.backward()
    print(f"Vòng {i+1}: x = {x.item():.4f}, dy/dx = {x.grad.item():.4f}")
    with torch.no_grad():
        x -= alpha * x.grad
    x.grad.zero_()

Vòng 1: x = 2.0000, dy/dx = 25.0000
Vòng 2: x = -0.5000, dy/dx = 3.7500
Vòng 3: x = -0.8750, dy/dx = 3.7969
Vòng 4: x = -1.2547, dy/dx = 4.7040
Vòng 5: x = -1.7251, dy/dx = 7.0274
Vòng 6: x = -2.4278, dy/dx = 12.9717
Vòng 7: x = -3.7250, dy/dx = 31.7268
Vòng 8: x = -6.8977, dy/dx = 120.1433
Vòng 9: x = -18.9120, dy/dx = 1002.3439
Vòng 10: x = -119.1464, dy/dx = 42116.0117


# BTVN 3:
Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 - 10) và y là số điểm được tính theo công thức y = 3x + 5 + noise
Với noise là một giá trị ngẫu nhiên nhỏ
1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad = True
2. Tính MSE
3. Tính Gradient
4. Cập nhật tham số w và b bằng Gradient Descent với Learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình

In [18]:
# BTVN 3: Linear Regression với Gradient Descent
import torch
import numpy as np

# Tạo dữ liệu giả lập
np.random.seed(42)
x_data = np.random.uniform(1, 10, 100)
noise = np.random.normal(0, 1, 100)
y_data = 3 * x_data + 5 + noise

x_tensor = torch.tensor(x_data, dtype=torch.float32).view(-1, 1)
y_tensor = torch.tensor(y_data, dtype=torch.float32).view(-1, 1)

# Khởi tạo tham số
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

alpha = 0.01
epochs = 100

for epoch in range(epochs):
    # Dự đoán
    y_pred = w * x_tensor + b
    
    # MSE
    loss = torch.mean((y_pred - y_tensor)**2)
    
    # Gradient
    loss.backward()
    
    # Cập nhật
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
    
    # Reset grad
    w.grad.zero_()
    b.grad.zero_()
    
    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}: Loss = {loss.item():.4f}, w = {w.item():.4f}, b = {b.item():.4f}")

print("Final: w ≈ 3, b ≈ 5")

Epoch 10: Loss = 8.0546, w = 3.8510, b = -0.6426
Epoch 20: Loss = 7.4929, w = 3.8154, b = -0.4090
Epoch 30: Loss = 6.9748, w = 3.7812, b = -0.1847
Epoch 40: Loss = 6.4968, w = 3.7483, b = 0.0308
Epoch 50: Loss = 6.0559, w = 3.7167, b = 0.2377
Epoch 60: Loss = 5.6491, w = 3.6863, b = 0.4364
Epoch 70: Loss = 5.2738, w = 3.6572, b = 0.6274
Epoch 80: Loss = 4.9277, w = 3.6292, b = 0.8107
Epoch 90: Loss = 4.6083, w = 3.6023, b = 0.9868
Epoch 100: Loss = 4.3137, w = 3.5765, b = 1.1560
Final: w ≈ 3, b ≈ 5


In [19]:
import torch
import numpy as np

In [20]:
torch.__version__

'2.9.1+cpu'

In [21]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [22]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [23]:
print(x.dtype)

torch.int64


In [24]:
print(x.type())

torch.LongTensor


In [25]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [26]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [27]:
#Copy and sharing
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [28]:
arr[0] = 99
print(x)

tensor([99,  1,  2,  3,  4])


In [29]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [30]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


# BTVN 4: Giải thích 2 trường hợp ở trên

# Giải thích BTVN 4:
1. `torch.from_numpy(arr)`: Tạo tensor từ numpy array, chia sẻ bộ nhớ. Thay đổi arr sẽ ảnh hưởng đến tensor.
2. `torch.tensor(arr)`: Tạo tensor từ numpy array, sao chép dữ liệu. Thay đổi arr không ảnh hưởng đến tensor.

# BTVN 5:
Bạn giúp thầy tạo tensor với 
empyty
zeros
ones
random
Reshape với view và view as

In [32]:
# BTVN 5: Tạo tensor với empty, zeros, ones, random và reshape
import torch

# Empty tensor
empty_tensor = torch.empty(3, 3)
print("Empty tensor:")
print(empty_tensor)

# Zeros tensor
zeros_tensor = torch.zeros(3, 3)
print("\nZeros tensor:")
print(zeros_tensor)

# Ones tensor
ones_tensor = torch.ones(3, 3)
print("\nOnes tensor:")
print(ones_tensor)

# Random tensor
random_tensor = torch.rand(3, 3)
print("\nRandom tensor:")
print(random_tensor)

# Reshape với view
reshaped_view = random_tensor.view(9)
print("\nReshaped with view (1D):")
print(reshaped_view)

# Reshape với view_as (giả sử có tensor khác)
other_tensor = torch.zeros(1, 9)
reshaped_view_as = random_tensor.view_as(other_tensor)
print("\nReshaped with view_as (1x9):")
print(reshaped_view_as)

Empty tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Zeros tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Ones tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Random tensor:
tensor([[0.8466, 0.3645, 0.5197],
        [0.1240, 0.8679, 0.3521],
        [0.8998, 0.6025, 0.0658]])

Reshaped with view (1D):
tensor([0.8466, 0.3645, 0.5197, 0.1240, 0.8679, 0.3521, 0.8998, 0.6025, 0.0658])

Reshaped with view_as (1x9):
tensor([[0.8466, 0.3645, 0.5197, 0.1240, 0.8679, 0.3521, 0.8998, 0.6025, 0.0658]])
